[ 2025-07-12 22:34:13,632 ] - 74 - INFO - Started data ingestion
[ 2025-07-12 22:43:48,006 ] - 52 - INFO - Spliiting the data as train and test set started
[ 2025-07-12 22:43:48,027 ] - 54 - INFO - Spliiting the data as train and test set ended
[ 2025-07-12 22:43:48,027 ] - 62 - INFO - Exporting train and test file path
[ 2025-07-12 22:43:49,334 ] - 65 - INFO - Exported train and test file path
[ 2025-07-12 22:43:49,573 ] - 33 - INFO - Expected columns: 50, Found: 81
[ 2025-07-12 22:43:49,573 ] - 96 - INFO - error occured in python script [D:\Network Security\networksecurity\components\data_validation.py] line number [74] error message ['NoneType' object has no attribute 'tb_lineno']
[ 2025-07-12 22:43:49,573 ] - 22 - INFO - error occured in python script [D:\Network Security\main.py] line number [19] error message [error occured in python script [D:\Network Security\networksecurity\components\data_validation.py] line number [74] error message ['NoneType' object has no attribute 'tb_lineno']]
